apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw2-deployment
  labels:
    hello_ec: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      hello_ec: helloworld
  template:
    metadata:
      labels:
        hello_ec: helloworld
    spec:
      containers:
      - name: helloworld
        image: xuranliu/hw2_hello_world_ec
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: default
spec:
  type: NodePort
  selector:
    hello_ec: helloworld
  ports:
  - port: 6000
    targetPort: 5000
    nodePort: 30001

